# Generated by Django 4.2.4 on 2023-08-17 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_alter_complain_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='home',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
