# Generated by Django 4.2.4 on 2023-08-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0003_complain_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='stand_number',
            field=models.IntegerField(),
        ),
    ]
