# Generated by Django 4.2.4 on 2023-08-17 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complaint', '0004_alter_complain_stand_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complain',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complain',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
