# Generated by Django 4.2.4 on 2023-08-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_owner_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='email',
            field=models.CharField(max_length=60),
        ),
    ]
