# Generated by Django 4.2.4 on 2023-08-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_owner_date_edited_alter_owner_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='stand',
        ),
    ]
