# Generated by Django 4.2.4 on 2023-08-17 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parameters', '0002_alter_complaintcategory_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhiteListGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_number', models.IntegerField()),
                ('home', models.CharField(max_length=200)),
                ('visit_code', models.CharField(max_length=60)),
                ('resident_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('visitor_name', models.CharField(max_length=60)),
                ('visitor_vehicle_reg_number', models.CharField(blank=True, max_length=20, null=True)),
                ('visitor_national_id', models.CharField(max_length=25)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhiteList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrived', models.DateTimeField(auto_now_add=True)),
                ('date_depature', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.transporttype')),
                ('visit_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.visitstatus')),
                ('white_list_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='whitelist.whitelistguest')),
            ],
        ),
    ]
