# Generated by Django 4.2.4 on 2023-08-13 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0002_alter_complaintcategory_status_and_more'),
        ('resident', '0003_alter_resident_date_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='email',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='resident',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.gender'),
        ),
    ]
