# Generated by Django 4.2.4 on 2023-08-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0004_alter_resident_email_alter_resident_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='email',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='phone_number3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='phone_number4',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
