# Generated by Django 4.1.7 on 2023-08-08 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stand', '0001_initial'),
        ('parameters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_code', models.CharField(max_length=60)),
                ('resident_phone_number', models.CharField(max_length=20)),
                ('visitor_name', models.CharField(max_length=60)),
                ('visitor_vehicle_reg_number', models.CharField(default='Foot', max_length=20)),
                ('visitor_national_id', models.CharField(max_length=25)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_arrived', models.DateTimeField(auto_now_add=True)),
                ('date_depature', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stand_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stand.stand')),
                ('transport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.transporttype')),
                ('visit_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.visitstatus')),
            ],
        ),
    ]
