# Generated by Django 4.2.4 on 2023-08-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='home',
            field=models.CharField(max_length=200),
        ),
    ]
