# Generated by Django 4.1.7 on 2023-08-08 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stand', '0001_initial'),
        ('parameters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_phone_number', models.CharField(max_length=20)),
                ('service_description', models.CharField(max_length=60)),
                ('service_provider_name', models.CharField(max_length=60)),
                ('service_provider_contact', models.CharField(max_length=60)),
                ('service_national_id', models.CharField(max_length=60)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('provider_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.providercategory')),
                ('service_request_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parameters.providerstatus')),
                ('stand_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stand.stand')),
            ],
        ),
    ]
