# Generated by Django 4.2.4 on 2023-08-14 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_home_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
