# Generated by Django 4.2.4 on 2023-08-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parameters', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintcategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='complaintstatus',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gender',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='homestatus',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='providercategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='providerstatus',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='standstatus',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transporttype',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='visitstatus',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
