# Generated by Django 4.2.4 on 2023-08-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stand', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
