# Generated by Django 4.2.4 on 2023-08-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stand', '0002_alter_stand_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stand',
            name='date_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
